### ISSUE TITLE
Chat application is not mobile friendly 

### ISSUE THREAD

**Issue by haykyte** [chatengine-io/react-chat-engine#1]
The 3 windows (Groups, Current Chat and Users) do not collapse well when shrinking the window. 

1. Lots of spaces windows when stacked
2. Multiple cases where the icons/styles and conflicting

![119780953_333899077858464_2823202753593741804_n](https://user-images.githubusercontent.com/65054511/93720254-e0c4b080-fb55-11ea-9a22-73377da42bad.png)

**Comment by alamorre** [comment]
Working on this bad boi rn
