### ISSUE TITLE
I can not get the user chats even though i have added publickey props

### ISSUE THREAD

**Issue by karteek-dev** [chatengine-io/react-chat-engine#14]
Fetchcharts message is not  showing the user chats
![Uploading Screenshot 2021-03-05 at 15.19.10.png…]()

**Comment by alamorre** [comment]
Sorry but I cannot see this image. Can you please re-upload?

**Comment by alamorre** [comment]
I'm looking into this now. I do know version 1.6.0 is stable.

For now run `npm install react-chat-engine@1.6.0` OR `yarn add react-chat-engine@1.6.0` while I work on this - thanks 👍👍
