### ISSUE TITLE
On sending image in chat feed, it isn't rendering,

### ISSUE THREAD

**Issue by XHauck404** [chatengine-io/react-chat-engine#17]
It's just showing a small block.

![image](https://user-images.githubusercontent.com/77182548/110818859-a988be00-82b3-11eb-8337-b43b80481e87.png)

**Comment by alamorre** [comment]
This issue is fixed in version @1.6.4 and above.

Thanks for bringing this up 😀

**Comment by alamorre** [comment]
Closed
