### ISSUE TITLE
CORS policy issue

### ISSUE THREAD

**Issue by danmugh** [chatengine-io/react-chat-engine#22]
I am working on a react project using chat engine and it all worked, but now I get an issue, access to XMLHttpRequest was blocked by CORS policy. **_Could you please help me resolve the issue??_**

<img width="526" alt="Screen Shot 2021-03-27 at 4 40 15 PM" src="https://user-images.githubusercontent.com/71265852/112722542-3d48c400-8f1b-11eb-9885-8ae400bcff99.png">

**Comment by LuaaDev** [comment]
I think you can solve this by using a .httaccess file
`
// Your can just allow code from any origin to access (not reccommended)
<IfModule mod_headers.c>
    Header set Access-Control-Allow-OriginAccess-Control-Allow-Origin "*"
</IfModule>

//or just allow requesting code from the origin-specific domain (recommended)

<IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin : http://localhost:3000
</IfModule>
`

**Comment by alamorre** [comment]
That's an error on my server and should be gone. I'll close this issue unless people are still having it 🤗

**Comment by eyegates** [comment]
Hi, it looks like the CORS issue is back I can't use the chat api today. I'm having CORS error on every call
