### ISSUE TITLE
${index} undefined in ChatCard.js

### ISSUE THREAD

**Issue by basileLeroy** [chatengine-io/react-chat-engine#34]
Good evening!

I encountered an issue with the ${index} in the ChatCard.js file.

![image](https://user-images.githubusercontent.com/72804463/113612026-90bfbe00-964f-11eb-83c4-4e94b4a33c36.png)

___

![image](https://user-images.githubusercontent.com/72804463/113611888-6bcb4b00-964f-11eb-86f5-af342e34a81a.png)

___

Hopefully this can help!

gtz

**Comment by alamorre** [comment]
Should be gone in version 1.8.7 👍👍

**Comment by basileLeroy** [comment]
1/2    
![image](https://user-images.githubusercontent.com/72804463/113717778-450f2200-96ec-11eb-9a0c-ff428ed0d722.png)
    
2/2    
![image](https://user-images.githubusercontent.com/72804463/113718136-a3d49b80-96ec-11eb-9c4b-6ce3d258f45c.png)

and the error message:
   
![image](https://user-images.githubusercontent.com/72804463/113717894-5d7f3c80-96ec-11eb-9c4c-42a3ea3ac28f.png)

or

![image](https://user-images.githubusercontent.com/72804463/113717974-78ea4780-96ec-11eb-95ad-cc92f0ec37e4.png)

**Comment by basileLeroy** [comment]
## The Issue above  seems to be fixed with the `1.8.8 version`.    
Thank you for that!    
     
---
    
I am getting this new error that "chats" can not be destructured:    

![image](https://user-images.githubusercontent.com/72804463/113835412-3c6e2880-978c-11eb-9fa6-c4b2b4580055.png)

I pushed it on [my repo](https://github.com/basileLeroy/ChatApp/blob/main/client/src/dev/components/ChatEngine/ChatList/index.js) , if you want to have a look.

**Comment by alamorre** [comment]
Fixed in your PR, it's not a react-chat-engine issue 😁
