### ISSUE TITLE
Display ChatFeed and messagebubbles

### ISSUE THREAD

**Issue by basileLeroy** [chatengine-io/react-chat-engine#39]
I have tried to have the messages in here, but this is what i get when I use:    
     
![image](https://user-images.githubusercontent.com/72804463/114088740-9e767d00-98b5-11eb-97b3-d1988ebd6180.png)

---    

![image](https://user-images.githubusercontent.com/72804463/114088604-7ab33700-98b5-11eb-8cc8-6bcabd7dcbb6.png)    
    
I supose it is something I missed, I also can't see new messages I have sent   
     
Have a great day!

**Comment by alamorre** [comment]
This is a bug on my end I'll get something out

**Comment by alamorre** [comment]
1.8.10 got this patched
