### ISSUE TITLE
can't able to create properly

### ISSUE THREAD

**Issue by 1s2akshi** [chatengine-io/react-chat-engine#40]
![Screenshot (623)](https://user-images.githubusercontent.com/40859556/114874383-e8adb000-9e19-11eb-8b2f-ddc672eeadd3.png)
but the result is
![Screenshot (624)](https://user-images.githubusercontent.com/40859556/114874807-4e01a100-9e1a-11eb-9771-a50be5c5967d.png)

**Comment by alamorre** [comment]
It needs to be `userName` capital N. 

This is a good catch because it should support both - I'll make it support both. Thanks for bringing this up!

**Comment by 1s2akshi** [comment]
> It needs to be `userName` capital N.
> 
> This is a good catch because it should support both - I'll make it support both. Thanks for bringing this up!

thankyou so much
