### ISSUE TITLE
why picture out lined not imported

### ISSUE THREAD

**Issue by 1s2akshi** [chatengine-io/react-chat-engine#41]
![Screenshot (626)](https://user-images.githubusercontent.com/40859556/114920126-b797a480-9e46-11eb-8a24-6e4e5d531d98.png)

i have imported pictureoutlined from ant icons

here is code
![Screenshot (625)](https://user-images.githubusercontent.com/40859556/114920254-ddbd4480-9e46-11eb-9cb1-added1bd0f64.png)

error is 
![Screenshot (627)](https://user-images.githubusercontent.com/40859556/114920366-fcbbd680-9e46-11eb-9b5d-bde4d0220551.png)
 please help

**Comment by alamorre** [comment]
Sorry this is an ant design issue, not mine
