### ISSUE TITLE
Attempted import error: 'getOrCreateChat' is not exported from 'react-chat-engine'.

### ISSUE THREAD

**Issue by shrsthameet** [chatengine-io/react-chat-engine#44]
While trying to import getOrCreateChat for implementing Direct Messaging(DMs) I am getting import error. Searched it but couldn't find the solution. Did anyone encounter same error?

**Comment by alamorre** [comment]
Version 1.8.11 has this fix and it's out now! Thanks for bringing this up i forgot to export it 😆

**Comment by shrsthameet** [comment]
lol.. spent hours figuring out what I did wrong.. Anyway thanks... 👍
