### ISSUE TITLE
Not loading Files and Pictures

### ISSUE THREAD

**Issue by asaser** [chatengine-io/react-chat-engine#47]
Hi, I can not open my files and pictures
![Untitled](https://user-images.githubusercontent.com/23105619/116241190-eaa23800-a764-11eb-9f74-3a9e69ab6b21.png)

My code is excatly the same like this guy from YT channel
https://www.youtube.com/watch?v=jcOKU9f86XE

Him repo: 
https://github.com/adrianhajdin/chat_application

How can I repair this?

**Comment by alamorre** [comment]
What do you mean by open, like expand them more?

If so the code isn't written to do this. Use the default <ChatEngine /> component without customizations
