### ISSUE TITLE
hideUI not working

### ISSUE THREAD

**Issue by ZhongchiLeoLi** [chatengine-io/react-chat-engine#50]
I tried to hide the default UI by passing the prop `hideUI` as `true`, but the interface still shows up.
My exact code is shown below.
```
<ChatEngine
    hideUI={true}
    projectID='df2a398d-a6b6-41ce-b4fe-915701fa969d'
    userName={chatConfig.userName}
    userSecret={chatConfig.userSecret}
/>
```

**Comment by alamorre** [comment]
Hey! The Hide UI prop is now gone. If you want a socket connection without the UI, use the Socket or ChatSocket component

https://chatengine.io/docs/sockets

Enjoy! 😉
