### ISSUE TITLE
Add no-admin requirement for letting people join a certain chat room!

### ISSUE THREAD

**Issue by frostzt** [chatengine-io/react-chat-engine#51]
Type: Feature Request
Feature Description: When using the API or simply when a user tries to invite some other person to a chat room, it is not allowed. This is itself trouble as the chat room can't grow. Implementing an invite system would be much more beneficial. Like when a user wants to invite someone he/she can send a link and the user can join!

**Comment by alamorre** [comment]
Hey 👋 I got some time to work on this Monday - assigning myself!

**Comment by alamorre** [comment]
Completed! Should be good to go 👍
