### ISSUE TITLE
WebSocket connection/entire Chat Engine server down?

### ISSUE THREAD

**Issue by ZhongchiLeoLi** [chatengine-io/react-chat-engine#55]
When I tried to log in to my app this morning I kept getting `WebSocket connection to '...' failed:` error, and when I tried to go into my project on chatengine.io to see what was wrong, the entire project is now empty:

![image](https://user-images.githubusercontent.com/60017285/116895509-46efd680-ac01-11eb-8473-7ec6a212e95b.png)

Even the Project ID is not showing.
Is the server may be down?

**Comment by ZhongchiLeoLi** [comment]
I am stressed since I just finished building my application yesterday with Chat Engine. Will I be able to get my project data back?

**Comment by alamorre** [comment]
Sorry its a front end issue, We're using env vars improperly gimme 45 mins

**Comment by alamorre** [comment]
Your data is fine right now - working on it

**Comment by ZhongchiLeoLi** [comment]
Thank you so much! Really appreciate all your work!

**Comment by alamorre** [comment]
Should be good to go now - thanks for waiting 🙏

**Comment by ZhongchiLeoLi** [comment]
YES it's working! Thank you for fixing it so quickly!
