### ISSUE TITLE
Installation Problem 

### ISSUE THREAD

**Issue by 19sajib** [chatengine-io/react-chat-engine#7]
### **I am having this error,>>**
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: chat-app@0.1.0
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-chat-engine@1.5.8
npm ERR! node_modules/react-chat-engine
npm ERR!   react-chat-engine@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Sajib\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sajib\AppData\Local\npm-cache\_logs\2021-01-30T04_34_50_115Z-debug.log

### **here is my package.json file:>>**
{
  "name": "chat-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@ant-design/icons": "^4.4.0",
    "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^11.2.3",
    "@testing-library/user-event": "^12.6.2",
    "axios": "^0.21.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.1",
    "web-vitals": "^0.2.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by alamorre** [comment]
Hey this is a good find. We're going to update react-chat-engine to be auto updating on react 17 now.

We added it to react-chat-engine@1.5.9 and it should be online tomorrow. We'll let you know when it's up 😀

**Comment by alamorre** [comment]
Good news it's going up now. Install react-chat-engine@1.5.9 or later and you should be fine!

**Comment by 19sajib** [comment]
yeah, that looks fine.
