### ISSUE TITLE
[Question] How to remove/disable the "new chat" component?

### ISSUE THREAD

**Issue by ekdnam** [chatengine-io/react-chat-engine#8]
I want to remove/disable this component.

![chat-engine (2)](https://user-images.githubusercontent.com/40426312/107884517-7739aa00-6f1b-11eb-954c-bec5049ceb8a.jpg)

How can I do that? Or any workarounds?

**Comment by alamorre** [comment]
In the docs, you can allow a custom render function for that form. If you add this prop in your <ChatEngine /> component: `renderNewChatForm={() => <div />}` then that form will be blank/hidden.

Here are the docs for more info: https://chatengine.io/docs/customize_ui#new_chat_form

Hope this helps 😀

**Comment by ekdnam** [comment]
Yes it worked! Thank you!
