### ISSUE TITLE
How to sync time zones ?

### ISSUE THREAD

**Issue by r12esh** [chatengine-io/react-chat-engine#84]
Time at my place is different and the timestamps in messages are different. Is there a way to display timestamps according to the viewer's area? Like if I visit from India timestamp is according to IST and for my friend in US the time stamp is according to his Time Zone.

**Comment by alamorre** [comment]
Thanks for opening this, yeah we support timezones with an offset={} prop!

Docs on changing the Chat Engine timezone are here https://chatengine.io/docs/timezones
