### ISSUE TITLE
function api sending axios request to wrong url

### ISSUE THREAD

**Issue by rayguo17** [chatengine-io/react-chat-engine#87]
Hey, i am using the react chat engine api, i import the getMyData function from node modules, following the documentation, but i get a 404 not found. So i check the source code in the node module as well as the chat engine api documentation in https://rest.chatengine.io/#1df17103-6a19-4666-8a4a-9baf8815dd01 , seems like, in the source code it is sending request to /chats/me, but in the document, should send request to /users/me .

**Comment by alamorre** [comment]
Great catch - just patched it.

Download 1.10.13 it should be out now 👍

**Comment by rayguo17** [comment]
Thanks for the response! Really appreciate your work! 🙌
