### ISSUE TITLE
Issues on site refresh

### ISSUE THREAD

**Issue by bug-author** [chatengine-io/react-chat-engine#89]
## Issue:
On site refresh, I face two issues:
- Last message is only visible in `Chat List`, however all previous messages disappear in `Chat Feed`.
- `Chat Feed` is rendered after some time, with first two messages enclosed in `p` tags. 

<br/>

### Desktop
![image](https://user-images.githubusercontent.com/48406637/128645780-0121ff18-e895-4b1e-bcc1-740b234cb3f5.png)

### Phone
![image](https://user-images.githubusercontent.com/48406637/128645806-4ea71c85-7091-4749-b615-c9b5f8465845.png)

**Comment by alamorre** [comment]
The patch has been released in 1.10.15, thanks for bringing this up! 👍
