### ISSUE TITLE
Dynamic require is not supported

### ISSUE THREAD

**Issue by NourH2000** [chatengine-io/react-chat-engine#98]
I am using a reactJs, and i got this issue 

Uncaught Error: Dynamic require of "/home/nour/Bureau/appliChat/node_modules/react-chat-engine/node_modules/react-quill/dist/quill.snow.css" is not supported
    __require chunk-IHTDASF6.js:11
    <anonymous> index.js:14 

### My  chat code : 
`import React from 'react'
import { useHistory } from 'react-router-dom'
import { ChatEngine } from 'react-chat-engine'
import { auth } from './firebase'

const Chat = () => {
    return (
        <div className='chats-page'>
   
    )
}

export default Chat

`

**Comment by DKBoston15** [comment]
@NourH2000 Are you using NextJS?

**Comment by alamorre** [comment]
NextJS is now supported. /documented here 👍 

https://chatengine.io/docs/tutorials/nextjs_chat_app

**Comment by alamorre** [comment]
NextJS is now supported. /documented here 👍 

https://chatengine.io/docs/tutorials/nextjs_chat_app
